apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clawtab-web
  namespace: clawtab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - clawtab.cc
      secretName: clawtab-cc-tls
  rules:
    - host: clawtab.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clawtab-web
                port:
                  number: 80
